# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'notBoredApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for notBoredApp
 pod 'Alamofire', '~> 5.4'

  target 'notBoredAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'notBoredAppUITests' do
    # Pods for testing
  end

end
